-- Tripistry_lsn Complete 22-Table Schema
DROP DATABASE IF EXISTS tripistry_lsn;
CREATE DATABASE tripistry_lsn;
USE tripistry_lsn;

SET FOREIGN_KEY_CHECKS = 0;

-- Clean up existing tables to ensure a fresh build
DROP TABLE IF EXISTS ENROLS, HAS_DESTINATION, INCLUDES_ATTRACTION, INCLUDES_RESTAURANT, INCLUDES_ACCOM, INCLUDES_FLIGHT;
DROP TABLE IF EXISTS ACCOMMODATION_AMENITIES, ATTRACTION, RESTAURANT, ACCOMMODATION, FLIGHT, DESTINATION;
DROP TABLE IF EXISTS REVIEW, PAYMENT, BOOKING, GROUP_TRIP, TRAVEL_PACKAGE;
DROP TABLE IF EXISTS TRAVELLER_PREFERENCE_TAGS, TRAVELLER, TRAVEL_AGENCY, USER, TRAVELLER_PREFERENCE;

-- 1. USER
CREATE TABLE USER (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    UserType ENUM('Traveller', 'Agency') NOT NULL,
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    Address VARCHAR(300),
    Phone VARCHAR(50)
);

-- 4. TRAVELLER_PREFERENCE (Created before TRAVELLER to satisfy FK)
CREATE TABLE TRAVELLER_PREFERENCE (
    PreferenceID INT AUTO_INCREMENT PRIMARY KEY,
    BudgetRange VARCHAR(100),
    TravelPace VARCHAR(50)
);

-- 2. TRAVELLER
CREATE TABLE TRAVELLER (
    UserID INT PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    PreferenceID INT,
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (PreferenceID) REFERENCES TRAVELLER_PREFERENCE(PreferenceID) ON DELETE SET NULL
);

-- 3. TRAVEL_AGENCY
CREATE TABLE TRAVEL_AGENCY (
    UserID INT PRIMARY KEY,
    AgencyName VARCHAR(200) NOT NULL,
    VerificationStatus VARCHAR(50) DEFAULT 'Pending',
    CommissionRate DECIMAL(5,2),
    FOREIGN KEY (UserID) REFERENCES USER(UserID) ON DELETE CASCADE
);

-- 5. TRAVELLER_PREFERENCE_TAGS
CREATE TABLE TRAVELLER_PREFERENCE_TAGS (
    PreferenceID INT,
    PreferenceTag VARCHAR(100),
    PRIMARY KEY (PreferenceID, PreferenceTag),
    FOREIGN KEY (PreferenceID) REFERENCES TRAVELLER_PREFERENCE(PreferenceID) ON DELETE CASCADE
);

-- 6. TRAVEL_PACKAGE
CREATE TABLE TRAVEL_PACKAGE (
    PackageID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Description TEXT,
    Price DECIMAL(12,2) NOT NULL,
    DurationDays INT DEFAULT 1,
    IsGroupTrip TINYINT(1) DEFAULT 0,
    Status VARCHAR(20) DEFAULT 'Active',
    ImageURL VARCHAR(500),
    AgencyID INT NOT NULL,
    FOREIGN KEY (AgencyID) REFERENCES TRAVEL_AGENCY(UserID) ON DELETE CASCADE
);

-- 7. GROUP_TRIP
CREATE TABLE GROUP_TRIP (
    GroupTripID INT AUTO_INCREMENT PRIMARY KEY,
    TripName VARCHAR(200) NOT NULL,
    MaxCapacity INT NOT NULL,
    Status VARCHAR(20) DEFAULT 'Open',
    AgencyID INT NOT NULL,
    PackageID INT NOT NULL,
    FOREIGN KEY (AgencyID) REFERENCES TRAVEL_AGENCY(UserID) ON DELETE CASCADE,
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE
);

-- 8. BOOKING
CREATE TABLE BOOKING (
    BookingID INT AUTO_INCREMENT PRIMARY KEY,
    BookingDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TotalCost DECIMAL(12,2) NOT NULL,
    Status VARCHAR(50) DEFAULT 'Pending',
    UserID INT NOT NULL,
    PackageID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES TRAVELLER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE
);

-- 9. PAYMENT
CREATE TABLE PAYMENT (
    BookingID INT,
    PaymentSeq INT,
    Amount DECIMAL(12,2) NOT NULL,
    PaymentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status VARCHAR(50) DEFAULT 'Completed',
    PRIMARY KEY (BookingID, PaymentSeq),
    FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID) ON DELETE CASCADE
);

-- 10. REVIEW
CREATE TABLE REVIEW (
    UserID INT,
    ReviewID INT AUTO_INCREMENT,
    PackageID INT NOT NULL,
    Comment TEXT,
    RatingScore TINYINT NOT NULL CHECK (RatingScore BETWEEN 1 AND 5),
    DatePosted DATETIME DEFAULT CURRENT_TIMESTAMP,
    BookingID INT,
    PRIMARY KEY (UserID, ReviewID),
    INDEX (ReviewID), -- Required by InnoDB for composite key with auto_increment
    FOREIGN KEY (UserID) REFERENCES TRAVELLER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (BookingID) REFERENCES BOOKING(BookingID) ON DELETE SET NULL,
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE
);

-- 11. DESTINATION
CREATE TABLE DESTINATION (
    DestinationID INT AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR(100) NOT NULL,
    Country VARCHAR(100) NOT NULL,
    Latitude DECIMAL(9,6),
    Longitude DECIMAL(9,6),
    Description TEXT,
    ImageURL VARCHAR(500),
    UNIQUE KEY unique_city_country (City, Country)
);

-- 12. FLIGHT
CREATE TABLE FLIGHT (
    FlightID INT AUTO_INCREMENT PRIMARY KEY,
    Airline VARCHAR(100) NOT NULL,
    FlightNumber VARCHAR(20) NOT NULL,
    DepartureCity VARCHAR(100) NOT NULL,
    ArrivalCity VARCHAR(100) NOT NULL,
    DepartureTime DATETIME NOT NULL,
    ArrivalTime DATETIME NOT NULL,
    Price DECIMAL(10,2) NOT NULL
);

-- 13. ACCOMMODATION
CREATE TABLE ACCOMMODATION (
    AccommodationID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Type VARCHAR(100),
    StarRating INT DEFAULT 3,
    PricePerNight DECIMAL(10,2) NOT NULL,
    Address VARCHAR(300),
    DestinationID INT,
    FOREIGN KEY (DestinationID) REFERENCES DESTINATION(DestinationID) ON DELETE SET NULL
);

-- 14. ACCOMMODATION_AMENITIES
CREATE TABLE ACCOMMODATION_AMENITIES (
    AccommodationID INT,
    Amenity VARCHAR(100),
    PRIMARY KEY (AccommodationID, Amenity),
    FOREIGN KEY (AccommodationID) REFERENCES ACCOMMODATION(AccommodationID) ON DELETE CASCADE
);

-- 15. RESTAURANT
CREATE TABLE RESTAURANT (
    RestaurantID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    CuisineType VARCHAR(100),
    PriceRange VARCHAR(50),
    Address VARCHAR(300),
    Rating DECIMAL(2,1) DEFAULT 0,
    DestinationID INT,
    FOREIGN KEY (DestinationID) REFERENCES DESTINATION(DestinationID) ON DELETE SET NULL,
    UNIQUE KEY unique_name_dest (Name(191), DestinationID)
);

-- 16. ATTRACTION
CREATE TABLE ATTRACTION (
    AttractionID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL,
    Type VARCHAR(100),
    EntryFee DECIMAL(10,2) DEFAULT 0,
    Description TEXT,
    OpeningHours VARCHAR(200),
    DestinationID INT,
    FOREIGN KEY (DestinationID) REFERENCES DESTINATION(DestinationID) ON DELETE SET NULL
);

-- 17. INCLUDES_FLIGHT
CREATE TABLE INCLUDES_FLIGHT (
    PackageID INT,
    FlightID INT,
    PRIMARY KEY (PackageID, FlightID),
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE,
    FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID) ON DELETE CASCADE
);

-- 18. INCLUDES_ACCOM
CREATE TABLE INCLUDES_ACCOM (
    PackageID INT,
    AccommodationID INT,
    PRIMARY KEY (PackageID, AccommodationID),
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE,
    FOREIGN KEY (AccommodationID) REFERENCES ACCOMMODATION(AccommodationID) ON DELETE CASCADE
);

-- 19. INCLUDES_RESTAURANT
CREATE TABLE INCLUDES_RESTAURANT (
    PackageID INT,
    RestaurantID INT,
    PRIMARY KEY (PackageID, RestaurantID),
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE,
    FOREIGN KEY (RestaurantID) REFERENCES RESTAURANT(RestaurantID) ON DELETE CASCADE
);

-- 20. INCLUDES_ATTRACTION
CREATE TABLE INCLUDES_ATTRACTION (
    PackageID INT,
    AttractionID INT,
    PRIMARY KEY (PackageID, AttractionID),
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE,
    FOREIGN KEY (AttractionID) REFERENCES ATTRACTION(AttractionID) ON DELETE CASCADE
);

-- 21. HAS_DESTINATION
CREATE TABLE HAS_DESTINATION (
    PackageID INT,
    DestinationID INT,
    PRIMARY KEY (PackageID, DestinationID),
    FOREIGN KEY (PackageID) REFERENCES TRAVEL_PACKAGE(PackageID) ON DELETE CASCADE,
    FOREIGN KEY (DestinationID) REFERENCES DESTINATION(DestinationID) ON DELETE CASCADE
);

-- 22. ENROLS
CREATE TABLE ENROLS (
    UserID INT,
    GroupTripID INT,
    PRIMARY KEY (UserID, GroupTripID),
    FOREIGN KEY (UserID) REFERENCES TRAVELLER(UserID) ON DELETE CASCADE,
    FOREIGN KEY (GroupTripID) REFERENCES GROUP_TRIP(GroupTripID) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;
